export const env = {
  BASEURL: process.env.BASEURL,
  NODE_PROD_BASEURL: process.env.NODE_PROD_BASEURL,
  MONGODB_URI: process.env.MONGODB_URI,
  CLOUDINARY_UPLOAD_PRESET: process.env.CLOUDINARY_UPLOAD_PRESET,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  COMMUNITY_SERVICES_USERS: process.env.COMMUNITY_SERVICES_USERS,
};
